In [1]:
%%bash
git clone https://github.com/ronakdm/input-marginalization.git
cd input-marginalization
git pull
cd ..

Already up to date.


fatal: destination path 'input-marginalization' already exists and is not an empty directory.


In [2]:
import torch

try:
    import transformers
except ModuleNotFoundError:
    !pip install transformers
    import transformers

In [3]:
import sys
sys.path.append("input-marginalization")

save_dir = "/content/gdrive/My Drive/input-marginalization"

from metrics import zero_erasure, unk_erasure, color_sentence

In [4]:
from google.colab import drive
drive.mount('/content/gdrive')

Drive already mounted at /content/gdrive; to attempt to forcibly remount, call drive.mount("/content/gdrive", force_remount=True).


Apply GPU acceleration before loading the models.

In [5]:
# cnn = torch.load(f"{save_dir}/cnn_sst2.pt")

In [6]:
bert = torch.load(f"{save_dir}/bert_sst2.pt")

In [7]:
sentences = [
  "a good piece of work more often than not .",
  "it ' s also , clearly , great fun .",
  "the best film about baseball to hit theaters since field of dreams .",
  "it ' s a bit disappointing that it only manages to be decent instead of dead brilliant ."
]

In [8]:
# BERT + Zero

for sentence in sentences:
  color_sentence(bert, sentence, zero_erasure)

a good piece of work more often than not .
it ' s also , clearly , great fun .
the best film about baseball to hit theaters since field of dreams .
it ' s a bit disappointing that it only manages to be decent instead of dead brilliant .


In [9]:
for sentence in sentences:
  print(zero_erasure(bert, sentence))

tensor([[0.2452, 0.2060, 2.3489, 1.0603, 0.4291, 0.6568, 0.0370, 0.2923, 1.4523,
         0.1529, 0.1097, 0.7434]])
tensor([[ 0.2788,  0.0369,  0.0456,  0.0937,  0.1258, -0.0276, -0.0650,  0.2334,
          0.8019,  0.6032,  0.0309,  1.9790]])
tensor([[ 1.2558e-01,  4.6897e-01,  2.5035e+00,  3.4609e-01,  2.5328e-01,
          1.5892e-02,  2.4835e-02,  6.3305e-03, -2.8607e-02,  1.4260e-01,
          5.5971e-02,  6.3859e-02, -6.0368e-04,  9.4455e-02,  2.4058e+00]])
tensor([[ 0.0786,  0.0812,  0.0353,  0.0505,  0.1493,  0.0119,  0.4049,  0.0678,
         -0.1164,  0.1323, -0.0250,  0.0459,  0.3402,  0.2039,  0.1932, -0.1268,
         -0.1693, -0.1646,  0.0687,  1.2566]])
