In [3]:
%%bash
git clone https://github.com/ronakdm/input-marginalization.git
cd input-marginalization
git pull
cd ..

Updating c23807f..a15fcc6
Fast-forward
 metrics.py | 60 ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
 1 file changed, 60 insertions(+)
 create mode 100644 metrics.py


fatal: destination path 'input-marginalization' already exists and is not an empty directory.
From https://github.com/ronakdm/input-marginalization
   c23807f..a15fcc6  main       -> origin/main


In [4]:
import torch

In [9]:
import sys
sys.path.append("input-marginalization")

from metrics import zero_erasure, unk_erasure

In [6]:
from google.colab import drive
drive.mount('/content/gdrive')
save_dir = "/content/gdrive/My Drive/input-marginalization"

Drive already mounted at /content/gdrive; to attempt to forcibly remount, call drive.mount("/content/gdrive", force_remount=True).


Apply GPU acceleration before loading the models.

In [7]:
cnn = torch.load(f"{save_dir}/cnn_sst2.pt")

In [8]:
bert = torch.load(f"{save_dir}/bert_sst2.pt")

In [11]:
sentences = [
  "a good piece of work more often than not .",
  "it ' s also , clearly , great fun .",
  "the best film about baseball to hit theaters since field of dreams .",
  "it ' s a bit disappointing that it only manages to be decent instead of dead brilliant ."
]

In [12]:
# BERT + Zero

for sentence in sentences:
  print(zero_erasure(bert, sentence))

# CNN + Zero

for sentence in sentences:
  print(zero_erasure(cnn, sentence))

# BERT + UNK

for sentence in sentences:
  print(unk_erasure(bert, sentence))

# CNN + UNK

for sentence in sentences:
  print(unk_erasure(cnn, sentence))

tensor([[0.4513, 0.3912, 5.1484, 1.9576, 0.6788, 1.1959, 0.0505, 0.6590, 3.0680,
         0.2871, 0.1845, 1.3795]])
tensor([[ 0.4941,  0.0623,  0.0716,  0.1391,  0.2452, -0.0377, -0.1223,  0.3507,
          1.3578,  0.8738,  0.0500,  3.9080]])
tensor([[ 2.2343e-01,  1.1295e+00,  5.1669e+00,  7.3011e-01,  4.6234e-01,
          2.7806e-02,  4.7479e-02,  4.2601e-03, -4.4263e-02,  3.4822e-01,
          1.1306e-01,  1.2601e-01,  2.7254e-02,  1.9085e-01,  5.3890e+00]])
tensor([[ 0.1088,  0.1339,  0.0624,  0.0837,  0.2274, -0.0157,  0.5407, -0.0204,
         -0.2026,  0.2152, -0.1340,  0.0707,  0.5725,  0.2908,  0.2974, -0.2238,
         -0.3172, -0.3685,  0.0661,  1.9807]])
tensor([[-0.5509,  0.7725,  1.4753,  1.7220,  1.5198,  1.8066,  0.4995,  2.1930,
         -0.5475,  0.6141,  0.5077, -0.0402]])
tensor([[ 0.0190, -0.3941,  0.8259, -0.8448, -0.6939,  1.5045,  2.1829,  1.5027,
          1.1406,  1.8970,  0.6017, -0.2630]])
tensor([[-0.0639,  0.1700, -0.7926,  0.5404,  0.4534,  0.0365, -0.2